### PR TITLE
Add SD-SC & SD-HC functionality. for AVR

### PR DESCRIPTION
**Pull request by PLyttle**
I propose these changes

- Add SD-SC and SD-HC capability to the SDcard driver
- add FAT16 reserved sectors
- add branch to CP/M BIOS Coldboot (0xFA00)
- correct missing -mmcu flag in AVR makefile

LP

### CODE REVIEW

**Comment by toyoshim** [comment]
Hi, PLyttle.
Sorry for overlooking your pull request.
I just notice your request recently, and it seems your patch introduce great new functionalities.
Now the request conflicts with my last patch, but I will try to manually resolve conflicts and merge it to my master branch.

**Comment by toyoshim** [comment]
Hum... the merged final code can not fit the mega88 program memory, exceeding by 500+ bytes on text.
Now that my new code can run on mega32u2 that has much more memory, I will enable the SC/HC supports only on such capable AVRs.

**Comment by toyoshim** [comment]
Aha, GCC's -flto did a nice job :)

**Comment by PLyttle** [comment]
I made a tiny board based on your work. It is hosted here:
https://www.retrobrewcomputers.org/doku.php?id=builderpages:rhkoolstar:start

I can send you a working version if you like, or some boards if you
want to put it together yourself.

Thanks for the great work

Rienk

**Comment by PLyttle** [comment]
Exciting stuff...

Yep. In order to get CP/M 3.0 to work you need to implement RAM paging.
This design has 4 32 kb pages.
I don't use FAT, because it slows down the machine too much. 

My snailmail address is:
Rienk Koolstra
Ooievaarstraat 72
1781 VR Den Helder
The Netherlands

I'll solder up a board and send it to you when I get your mail address.
The good part of using an ATMega88 is it is CHEAP. 50 cents each. An
ATMega32u2 is 10 times as expensive :-(

**Comment by toyoshim** [comment]
deleted the last comment since personal info was mentioned in public, maybe mistakenly?

**Pull request merged**
